name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['{{ cookiecutter.python_version }}']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
      
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      run: uv python install {% raw %}${{ matrix.python-version }}{% endraw %}
      
    - name: Install dependencies
      run: uv sync --all-extras
        
    - name: Lint and format
      run: |
        uv run ruff check {{ cookiecutter.package_name }} tests
        uv run ruff format --check {{ cookiecutter.package_name }} tests
        
    - name: Test
      run: uv run pytest tests